config/routes.rb
Rails.application.routes.draw do
  root "pets#index"
  resources :listings
  resources :pets
  resources :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  default_scope { where("age > 2") }
 
  scope :male_pet, ->{ where(gender: "Male") }
  scope :cat_pet, ->{ where(pet_type: "Cat") } 
  scope :age_less_than_5, ->{ where("age < 5") }
  scope :age_greater_than_10, ->{ where("age > 10") }
  scope :age_larger_than_5, ->{ where("age > 5") }

  def self.get_age_larger_than_5  
    where("age > 5")  
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pets
  validates :name, presence: true    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:name, :price, :status)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:name, :gender, :pet_type, :age)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetHotel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="container">  
      <%= yield %>
    </div> 
    <%= render "shared/footer" %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.name %></td>
        <td><%= listing.price %></td>
        <td><%= listing.status %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Show</h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <p>
        <strong>Name:</strong>
        <%= @listing.name %>
      </p>
    </li>
    <li class="list-group-item">
      <p>
        <strong>Price:</strong>
        <%= @listing.price %>
      </p>    
    </li>
    <li class="list-group-item">
      <p>
        <strong>Status:</strong>
        <%= @listing.status %>
      </p>    
    </li>
  </ul>
  <div class="card-body">
    <%= link_to 'Edit', edit_listing_path(@listing), class:"card-link"%>
    <%= link_to 'Back', listings_path, class:"card-link" %>
  </div>
</div>

app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name , class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :gender %>
    <%= form.text_field :gender , class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :type %>
    <%= form.text_field :type , class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :age %>
    <%= form.text_field :age, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary btn-sm" %>
  </div>  
<% end %>
  

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Type</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.gender %></td>
        <td><%= pet.pet_type %></td>
        <td><%= pet.age %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Show</h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <p>
        <strong>Name:</strong>
        <%= @pet.name %>
      </p>
    </li>
    <li class="list-group-item">
      <p>
        <strong>Gender:</strong>
        <%= @pet.gender %>
      </p>    
    </li>
    <li class="list-group-item">
      <p>
        <strong>Type:</strong>
        <%= @pet.pet_type %>
      </p>    
    </li>    
    <li class="list-group-item">
      <p>
        <strong>Age:</strong>
        <%= @pet.age %>
      </p>    
    </li>  
  </ul>
  <div class="card-body">
    <%= link_to 'Edit', edit_pet_path(@pet), class:"card-link"%>
    <%= link_to 'Back', pets_path, class:"card-link" %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
<div class="row">
  <div class="col-12 col-md">
    <img class="mb-2" src="/docs/4.5/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
    <small class="d-block mb-3 text-muted">© 2017-2020</small>
  </div>
  <div class="col-6 col-md">
    <h5>Features</h5>
    <ul class="list-unstyled text-small">
      <li><a class="text-muted" href="#">Cool stuff</a></li>
      <li><a class="text-muted" href="#">Random feature</a></li>
      <li><a class="text-muted" href="#">Team feature</a></li>
      <li><a class="text-muted" href="#">Stuff for developers</a></li>
      <li><a class="text-muted" href="#">Another one</a></li>
      <li><a class="text-muted" href="#">Last time</a></li>
    </ul>
  </div>
  <div class="col-6 col-md">
    <h5>Resources</h5>
    <ul class="list-unstyled text-small">
      <li><a class="text-muted" href="#">Resource</a></li>
      <li><a class="text-muted" href="#">Resource name</a></li>
      <li><a class="text-muted" href="#">Another resource</a></li>
      <li><a class="text-muted" href="#">Final resource</a></li>
    </ul>
  </div>
  <div class="col-6 col-md">
    <h5>About</h5>
    <ul class="list-unstyled text-small">
      <li><a class="text-muted" href="#">Team</a></li>
      <li><a class="text-muted" href="#">Locations</a></li>
      <li><a class="text-muted" href="#">Privacy</a></li>
      <li><a class="text-muted" href="#">Terms</a></li>
    </ul>
  </div>
</div>
</footer>

app/views/shared/_header.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
<h5 class="my-0 mr-md-auto font-weight-normal">Pet Hotel</h5>
<nav class="my-2 my-md-0 mr-md-3">
  <%= link_to "User", users_path, class:"p-2 text-dark" %>
  <%= link_to "Pets", pets_path, class:"p-2 text-dark" %>
  <%= link_to "Listing", listings_path, class:"p-2 text-dark" %>
</nav>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.phone_number %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Show</h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <p>
        <strong>Name:</strong>
        <%= @user.name %>
      </p>
    </li>
    <li class="list-group-item">
      <p>
        <strong>Phone number:</strong>
        <%= @user.phone_number %>
      </p>    
    </li>
  </ul>
  <div class="card-body">
    <%= link_to 'Edit', edit_user_path(@user), class:"card-link"%>
    <%= link_to 'Back', users_path, class:"card-link" %>
  </div>
</div>